import test from 'node:test';import assert from 'node:assert/strict';
import {DEFAULT_PROGRESSION,validateProgression,progressionAt} from '../dist/progression.js';
import {hazardAt,createChallenge,stepChallenge} from '../dist/challenge.js';
test('progression rejects unordered stages, empty attacks and unsafe values',()=>{const p=structuredClone(DEFAULT_PROGRESSION);assert.deepEqual(validateProgression(p),p);p.stages[1].atSec=0;assert.throws(()=>validateProgression(p));p.stages[1].atSec=30;p.stages[0].intervalSec=0;assert.throws(()=>validateProgression(p));});
test('progression reports exact boundaries and holds the final stage',()=>{assert.equal(progressionAt(29999).level,1);assert.equal(progressionAt(30000).level,2);assert.equal(progressionAt(10000000).next,null);});
test('progression rejects a one-wide eight-cell sword',()=>{const p=structuredClone(DEFAULT_PROGRESSION);p.stages[0].length=8;assert.throws(()=>validateProgression(p),/1×8/);});
test('timed schedule includes swords early and multiple attacks in the first minute',()=>{const hazards=Array.from({length:12},(_,i)=>hazardAt(42,i));assert.ok(hazards[0].at<=9000);assert.ok(hazards[0].attacks.some(a=>a.kind==='vertical'));assert.ok(hazards.filter(h=>h.at<60000).length>=5);});
test('custom endless progression changes actual attacks while timed remains standard',()=>{const progression=structuredClone(DEFAULT_PROGRESSION);progression.stages[0]={...progression.stages[0],swords:2,width:3,length:6,sprinkles:7};const c=createChallenge({mode:'endless',progression});assert.equal(c.nextHazard.attacks.filter(a=>a.kind!=='sprinkle').length,2);const t=createChallenge({mode:'timed',progression});assert.equal(t.nextHazard.attacks.filter(a=>a.kind!=='sprinkle').length,1);});
test('queued first wave is applied on the next actual placement',()=>{const c=createChallenge();c.elapsed=c.nextHazard.at;stepChallenge(c,1);const p=c.entries[0].game.players[0];assert.equal(p.incoming.length,1);p.active.y=0;p.lock=350;stepChallenge(c,1);for(let i=0;i<80;i++)stepChallenge(c,16);assert.ok(p.board.flat().some(cell=>cell?.strike));});
